const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const code=fs.readFileSync(require('node:path').join(__dirname,'../player.js'),'utf8');
function bridge(){const parent={messages:[],postMessage(data,origin){this.messages.push({data,origin});}},handlers={};const node=()=>({children:[],listeners:{},attributes:{},append(x){this.children.push(x);},replaceChildren(x){this.children=[x];},setAttribute(k,v){this.attributes[k]=v;},addEventListener(k,fn){this.listeners[k]=fn;}});
const document={head:node(),body:node(),getElementById:()=>node(),createElement:()=>node()};const window={parent,addEventListener:(k,fn)=>handlers[k]=fn};vm.runInNewContext(code,{window,document,location:{origin:'https://example.test'},URL});return{document,parent,send:(data,origin='https://example.test',source=parent)=>handlers.message({data,origin,source})};}
const init={type:'kids-player-init',provider:'https://provider.example',videoId:'vid00000001',title:'<img onerror=x>'};
test('trusted bridge restricts frame path to this exact approved video',()=>{const a=bridge();a.send(init);assert.equal(a.document.head.children[0].content,"frame-src https://provider.example/embed/vid00000001; object-src 'none'; base-uri 'none'");const frame=a.document.body.children[0];assert.equal(frame.title,init.title);assert.match(frame.attributes.sandbox,/allow-same-origin/);assert.doesNotMatch(frame.attributes.sandbox,/top-navigation|popups|forms/);const url=new URL(frame.src);assert.equal(url.searchParams.get('related_videos'),'false');assert.equal(url.searchParams.get('continue'),'0');frame.listeners.load();assert.equal(a.parent.messages[0].data.type,'kids-player-ready');});
test('wrong origin/source messages cannot initialize the bridge',()=>{const a=bridge();a.send(init,'https://provider.example');a.send(init,'https://example.test',{});assert.equal(a.document.body.children.length,0);});
test('bridge rejects unsafe providers, credentials and invalid video IDs',()=>{for(const provider of ['javascript:alert(1)','http://provider.example','https://u:p@provider.example','https://example.test','https://provider.example/path']){const a=bridge();a.send({...init,provider});assert.equal(a.document.body.children.length,0);}const a=bridge();a.send({...init,videoId:'bad/<script>'});assert.equal(a.document.body.children.length,0);});
test('second init cannot change the immutable video policy in an existing bridge',()=>{const a=bridge();a.send(init);a.send({...init,videoId:'vid00000002'});assert.equal(a.document.head.children.length,1);assert.match(a.document.body.children[0].src,/vid00000001/);});
