pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io'; content { includeGroupByRegex 'com\\.github\\.(TeamNewPipe|teamnewpipe).*' } }
    }
}
rootProject.name = 'KidsYouTube'
include ':app'
